Game/Game/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("master.urls")),
    path("admin/", admin.site.urls),
]

Game/master/urls.py
from django.urls import path

from . import views

app_name = "master"

urlpatterns = [
	path("", views.index, name="index"),
    path("register/", views.register, name="register"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("profile/", views.profile, name="profile"),
    path("worker/", views.worker, name="worker"),
    path("storage/", views.storage, name="storage"),
    path("reputation/", views.reputation, name="reputation"),
	path("resource/", views.resource, name="resource"),
    path("tax/", views.tax, name="tax"),
    path("about/", views.about, name="about"),
]

Game/master/models.py
from django.db import models
from django.conf import settings
from django.utils.timezone import now

class Profile(models.Model):
    user = models.OneToOneField(to = settings.AUTH_USER_MODEL, on_delete = models.CASCADE, blank = False, null = False)
    money = models.PositiveBigIntegerField(default = 10000)
    reputation = models.IntegerField(default = 0)
    products = models.IntegerField(default = 0)
    storage = models.IntegerField(default = 5000)
    production = models.IntegerField(default = 3)
    resource = models.IntegerField(default = 20000)
    tax = models.IntegerField(default = 0)
    level = models.IntegerField(default = 0)
    selling_mult = models.IntegerField(default = 8)
    last_active = models.DateTimeField(default = now)

Game/master/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.utils.timezone import now

from math import floor, ceil
from .models import Profile
from . import definitions

def calc_prod(player):
	call_time = now()
	prod_duration = call_time - player.last_active
	ticks = prod_duration.seconds
	total_production = ticks * player.production

	# Available production
	if player.resource < total_production * 5:
		total_production = ceil(player.resource / 5)
	
	# Available storage
	if (player.storage - player.products) < (player.production * ticks):
		total_production = (player.storage - player.products)
	
	player.products += total_production
	player.resource -= total_production * 5
	player.last_active = now()
	player.save()

@login_required
def index(request):
	context = {}
	player = Profile.objects.get(user = request.user)
	calc_prod(player)
	context["player"] = player
	if request.method == "POST":
		player.tax += player.products
		player.money += ( player.products * player.selling_mult )
		player.products -= player.products
		player.save()
	return render(request = request, template_name = "index.html", context = context)

@login_required
def profile(request):
	context = {}
	player = Profile.objects.get(user = request.user)
	calc_prod(player)
	context["player"] = player
	return render(request = request, template_name = "profile.html", context = context)

@login_required
def worker(request):
	context = {}
	context["workers"] = definitions.workers
	context["player"] = Profile.objects.get(user = request.user)
	if request.method == "POST":
		id = int(request.POST.get("id"))
		target = definitions.workers[id]
		player = context["player"]
		if player.money >= target["cost"] and player.level >= target["level"]:
			player.money -= target["cost"]
			player.production += target["production"]
			player.save()
		else:
			print("Not enough.")
	return render(request = request, template_name = "worker.html", context = context)

@login_required
def storage(request):
	context = {}
	context["storages"] = definitions.storages
	context["player"] = Profile.objects.get(user = request.user)
	if request.method == "POST":
		id = int(request.POST.get("id"))
		target = definitions.storages[id]
		player = context["player"]
		if player.money >= target["cost"] and player.level >= target["level"] and (player.tax > 20000 + 20000 * player.level):
			player.money -= target["cost"]
			player.storage += target["storage"]
			player.save()
		else:
			print("Not enough.")
	return render(request = request, template_name = "storage.html", context = context)

@login_required
def reputation(request):
	context = {}
	context["reps"] = definitions.reputations
	context["player"] = Profile.objects.get(user = request.user)
	if request.method == "POST":
		id = int(request.POST.get("id"))
		target = definitions.reputations[id]
		player = context["player"]
		if player.money >= target["cost"]:
			player.money -= target["cost"]
			player.reputation += target["rep"]
			if player.reputation >= definitions.level_req[player.level]:
				player.level += 1
				player.selling_mult = definitions.selling_mult[player.level]
			player.save()
		else:
			print("Not enough.")
	return render(request = request, template_name = "reputation.html", context = context)

@login_required
def resource(request):
	context = {}
	context["player"] = Profile.objects.get(user = request.user)
	if request.method == "POST":
		resource_request = int(request.POST.get("resource"))
		player = context["player"]
		if player.money >= resource_request:
			player.money -= resource_request
			player.resource += resource_request
			player.save()
		else:
			print("Not enough.")
	return render(request = request, template_name = "resource.html", context = context)

@login_required
def tax(request):
	context = {}
	context["player"] = Profile.objects.get(user = request.user)
	context["tax_limit"] = 20000 + 20000 * context["player"].level
	if request.method == "POST":
		tax_request = int(request.POST.get("resource"))
		player = context["player"]
		if player.money >= tax_request and tax_request < player.tax:
			player.money -= tax_request
			player.tax -= tax_request
			player.save()
		else:
			print("Not enough. Or overpaid.")
	return render(request = request, template_name = "tax.html", context = context)

def register(request):
	context = {}
	if request.method == "POST":
		form = UserCreationForm(request.POST)
		if form.is_valid():
			user = form.save()
			profile = Profile(user = user)
			profile.save()
			auth_login(request = request, user = user)
			return redirect("master:index")
		else:
			print(form.errors)
			print(form.error_messages)
			context["user_form"] = UserCreationForm()
			return render(request = request, template_name = "register.html", context = context)
	else:
		context["user_form"] = UserCreationForm()
	return render(request = request, template_name = "register.html", context = context)

def login(request):
	context = {}
	if request.method == "POST":
		user = authenticate(request, username = request.POST.get("username"), password = request.POST.get("password"))
		if user is not None:
			auth_login(request, user)
			return redirect("master:index")
		else:
			return render(request = request, template_name = "index.html", context = context)
	else:
		pass
	return render(request = request, template_name = "login.html", context = context)

@login_required
def logout(request):
	context = {}
	auth_logout(request = request)
	return redirect("master:login")

def about(request):
	context = {}
	return render(request = request, template_name = "about.html", context = context)

Game/master/templates/about.html
{% extends "./base.html" %}

{% block content %}       

<div class="container text-center fs-5">
	<div>
		Created by Orkun AVCI in 24 hours as a replica of the original game app <a href="https://play.google.com/store/apps/details?id=com.florapp.ticaretoyunufabrikayonet"> found here.</a>
	</div>
	<div>
		Don't expect updates, but feel free to hit me up on these links:
	</div>
	<div class="container m-3">
		<a href="https://github.com/OrkunAvci" class="mx-2">Github</a>
		<a href="https://twitter.com/orkunavci28" class="mx-2">Twitter</a>
	</div>
</div>

{% endblock %}

Game/master/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
	<title>Factory Game</title>
</head>
<body class="" data-bs-theme="dark">
	{% include "navbar.html" %}
	<div class="w-75 mx-auto my-5">
		{% block content %}{% endblock %}
	</div>
</body>
</html>

Game/master/templates/index.html
{% extends "base.html" %}

{% block content %}

{% include "./showcase.html" %}
<div class="conatiner text-center">
	<div class="col-12 my-3">
		<form action="{% url 'master:index' %}" method="post">
			{% csrf_token %}
			<button class="btn btn-primary">Sell All</button>
		</form>
	</div>
</div>

{% endblock %}

Game/master/templates/login.html
{% extends "./base.html" %}

{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
	{% if user.is_authenticated %}
		<p>Your account doesn't have access to this page. To proceed, please login with an account that has access.</p>
	{% else %}
		<p>Please login to see this page.</p>
	{% endif %}
{% endif %}

<!--Login-->
<div class="container py-5 w-50">
	<h1 class="text-center">Login</h1>
	<form method="post" action="{% url 'master:login' %}">
		{% csrf_token %}
		<div class="mb-3">
			<label for="username" class="form-label">Username</label>
			<input type="text" class="form-control" id="username" name="username" aria-describedby="username">
		</div>
		<div class="mb-3">
			<label for="password" class="form-label">Password</label>
			<input type="password" class="form-control" id="password" name="password">
		</div>
		<input type="hidden" name="next" value="{{ next }}">
		<div class="text-center my-2">
			<button type="submit" class="btn btn-primary">Login</button>
		</di>
	</form>
	<p class="text-center my-4">
		Don't have an account? <a href="{% url 'master:register' %}">Create an account</a>.
	</p>
</div>

{% endblock %}

Game/master/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-black sticky-top d-flex">
	<div class="container-fluid">
		{% if not user.is_authenticated %}
			<div class="navbar-nav d-flex flex-col">
				<a class="nav-link active p-3" href="{% url 'master:login' %}">Login</a>
			</div>
		{% else %}
		<div class="navbar-nav d-flex flex-col">
			<a class="nav-link active p-3" href="{% url 'master:index' %}">Home</a>
		</div>
		<div class="navbar-nav d-flex flex-col">
			<a class="nav-link active p-3" href="{% url 'master:worker' %}">Worker</a>
		</div>
		<div class="navbar-nav d-flex flex-col">
			<a class="nav-link active p-3" href="{% url 'master:storage' %}">Storage</a>
		</div>
		<div class="navbar-nav d-flex flex-col">
			<a class="nav-link active p-3" href="{% url 'master:reputation' %}">Reputation</a>
		</div>
		<div class="navbar-nav d-flex flex-col">
			<a class="nav-link active p-3" href="{% url 'master:resource' %}">Resource</a>
		</div>
		<div class="navbar-nav d-flex flex-col">
			<a class="nav-link active p-3" href="{% url 'master:tax' %}">Taxes</a>
		</div>
		<div class="navbar-nav d-flex flex-col">
			<a class="nav-link active p-3" href="{% url 'master:profile' %}">Profile</a>
		</div>
		{% endif %}
		<div class="navbar-nav d-flex flex-col">
			<a class="nav-link active p-3" href="{% url 'master:about' %}">About</a>
		</div>
	</div>
</nav>

Game/master/templates/profile.html
{% extends "base.html" %}

{% block content %}

{% include "./showcase.html" %}
<div class="conatiner text-center">
	<div class="col-12 my-3">
		<a href="{% url 'master:logout' %}" class="btn btn-danger">Logout</a>
	</div>
</div>


{% endblock %}

Game/master/templates/register.html
{% extends "./base.html" %}

{% block content %}       

<!--Register--> 
<div class="container py-5 w-50">
	<h1 class="text-center">Register</h1>
	<form method="post" action="{% url 'master:register' %}">
		{% csrf_token %}
		<div class="mb-3">
			<label for="username" class="form-label">Username</label>
			<input type="text" class="form-control" id="username" name="username" aria-describedby="username">
		</div>
		<div class="mb-3">
			<label for="password1" class="form-label">Password</label>
			<input type="password" class="form-control" id="password1" name="password1">
		</div>
		<div class="mb-3">
			<label for="password2" class="form-label">Password Reconfirmation</label>
			<input type="password" class="form-control" id="password2" name="password2">
		</div>
			<div class="mb-3 text-center my-5">
			<button type="submit" class="btn btn-primary">Register</button>
		</div>
	</form>
</div>

{% endblock %}

Game/master/templates/reputation.html
{% extends "base.html" %}

{% block content %}

<div class="container text-center">
	<div class="fs-4">Money: {{ player.money }}</div>
	<div class="fs-4">Reputation: {{ player.reputation }}</div>
</div>

<div class="container-fluid text-center d-flex flex-row">
	{% for rep in reps %}
		<div class="card m-5 w-100">
			<div class="card-header">
				{{ rep.name }}
			</div>
			<div class="card-body">
				<p class="card-text">Cost: {{ rep.cost }}</p>
				<p class="card-text">Reputation: {{ rep.rep }}</p>
				<form action="{% url 'master:reputation'%}" method="post">
					{% csrf_token %}
					<input type="hidden" value="{{ rep.id }}" name="id"/>
					<button type="submit" class="btn btn-primary">Buy</button>
				</form>
			</div>
		</div>
	{% endfor %}
</div>

{% endblock %}

Game/master/templates/resource.html
{% extends "base.html" %}

{% block content %}
{% load humanize %}

<div class="container text-center">
	<div class="fs-4">Money: {{ player.money|intcomma }}</div>
	<div class="fs-4">Resource: {{ player.resource|intcomma }}</div>
</div>

<div class="container-fluid text-center">
	<form class="position-relative" action="{% url 'master:resource'%}" method="post">
		{% csrf_token %}
		<label for="resource" class="form-label fs-3">How many resources do you wish to buy?</label>
		<div class="mx-auto my-5 position-relative w-25">
			<input type="number" class="form-control" id="resource" name="resource">
			<div>1 Resource = 1$</div>
		</div>
		<div class="col-12 my-3">
			<button type="submit" class="btn btn-primary">Buy</button>
		</div>
	</form>
</div>

{% endblock %}

Game/master/templates/showcase.html
{% load humanize %}
<div class="container text-center w-50 border">
	<div class="row">
		<div class="col border py-3">
			Money
		</div>
		<div class="col border py-3">
			{{ player.money|intcomma }}
		</div>
	</div>
	<div class="row">
		<div class="col border py-3">
			Production
		</div>
		<div class="col border py-3">
			{{ player.production|intcomma }}
		</div>
	</div>
	<div class="row">
		<div class="col border py-3">
			Products | Storage
		</div>
		<div class="col border py-3">
			{{ player.products|intcomma }} | {{ player.storage|intcomma }}
		</div>
	</div>
	<div class="row">
		<div class="col border py-3">
			Resource
		</div>
		<div class="col border py-3">
			{{ player.resource|intcomma }}
		</div>
	</div>
	<div class="row">
		<div class="col border py-3">
			Tax
		</div>
		<div class="col border py-3">
			{{ player.tax|intcomma }}
		</div>
	</div>
	<div class="row">
		<div class="col border py-3">
			Level | Reputation
		</div>
		<div class="col border py-3">
			{{ player.level|intcomma }} | {{ player.reputation|intcomma }}
		</div>
	</div>
	<div class="row">
		<div class="col border py-3">
			Selling Multiplier
		</div>
		<div class="col border py-3">
			{{ player.selling_mult|intcomma }}
		</div>
	</div>
</div>

Game/master/templates/storage.html
{% extends "base.html" %}

{% block content %}
{% load humanize %}

<div class="container text-center">
	<div class="fs-4">Money: {{ player.money|intcomma }}</div>
	<div class="fs-4">Storage: {{ player.storage|intcomma }}</div>
</div>

<div class="container-fluid text-center d-flex flex-row">
	{% for storage in storages %}
		<div class="card m-5 w-100">
			<div class="card-header">
				{{ storage.name }}
			</div>
			<div class="card-body">
				<p class="card-text">Cost: {{ storage.cost }}</p>
				<p class="card-text">Capacity: {{ storage.storage }}</p>
				<p class="card-text">Level: {{ storage.level }}</p>
				<form action="{% url 'master:storage'%}" method="post">
					{% csrf_token %}
					<input type="hidden" value="{{ storage.id }}" name="id"/>
					<button type="submit" class="btn btn-primary">Buy</button>
				</form>
			</div>
		</div>
	{% endfor %}
</div>

{% endblock %}

Game/master/templates/tax.html
{% extends "base.html" %}

{% block content %}
{% load humanize %}

<div class="container text-center">
	<div class="fs-4">Money: {{ player.money|intcomma }}</div>
	<div class="fs-4">Tax: {{ player.tax|intcomma }}</div>
	<div class="fs-4">Tax Limit: {{ tax_limit|intcomma }}</div>
</div>

<div class="container-fluid text-center">
	<form class="position-relative" action="{% url 'master:tax'%}" method="post">
		{% csrf_token %}
		<label for="resource" class="form-label fs-3 my-4">Pay your taxes.</label>
		<div class="mx-auto my-5 position-relative w-25">
			<input type="number" class="form-control" id="resource" name="resource">
			<div>1 Resource = 1$</div>
		</div>
		<div class="col-12 my-3">
			<button type="submit" class="btn btn-primary">Buy</button>
		</div>
	</form>
</div>

{% endblock %}

Game/master/templates/worker.html
{% extends "base.html" %}

{% block content %}
{% load humanize %}

<div class="container text-center">
	<div class="fs-4">Money: {{ player.money|intcomma }}</div>
	<div class="fs-4">Production: {{ player.production|intcomma }}</div>
</div>

<div class="container-fluid text-center d-flex flex-row">
	{% for worker in workers %}
		<div class="card m-5 w-100">
			<div class="card-header">
				{{ worker.name }}
			</div>
			<div class="card-body">
				<p class="card-text">Cost: {{ worker.cost }}</p>
				<p class="card-text">Production: {{ worker.production }}</p>
				<p class="card-text">Level: {{ worker.level }}</p>
				<form action="{% url 'master:worker'%}" method="post">
					{% csrf_token %}
					<input type="hidden" value="{{ worker.id }}" name="id"/>
					<button type="submit" class="btn btn-primary">Hire</button>
				</form>
			</div>
		</div>
	{% endfor %}
</div>

{% endblock %}